Rails:
  Enabled: true
AllCops:
  Include:
    - '**/Gemfile'
    - '**/Rakefile'
    - 'config.ru'
  Exclude:
   - 'bin/*'
   - 'db/seeds.rb'
   - 'db/schema.rb'
   - 'vendor/bundle/**/*'
   - 'config/application.rb'
   - 'config/routes.rb'
   - 'config/environments/*'
   - 'config/initializers/*'
   - 'db/migrate/*'
   - 'test/test_helper.rb'
   - '**/spec/spec_helper.rb'
   - '**/spec/rails_helper.rb'
   - '**/Rakefile'
   - '**/lib/**/*'

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/ClassLength:
  CountComments: false  # count full line comments?

Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 100

Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 10

Style/AsciiComments:
  Enabled: false
