language: ruby
rvm:
- 2.1.0
env:
- DB=postgresql
script:
- bundle exec rspec spec
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database test_pgsql;' -U postgres
