language: ruby
rvm:
- 2.7.2
env:
- DB=postgresql
script:
- bundle exec rspec spec
addons:
  postgresql: '9.4'
before_install:
- gem update --system
- gem install bundler
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database blog_test;' -U postgres
- bundle exec rake db:migrate
install: bundle install --jobs=3 --retry=3
